apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
# we can define global "provision creds"
# or we can create custom creds for "multi tenancy".
# It allows "clients" to essentially BYO credentials
kind: AzureClusterIdentity
metadata:
  namespace: default
  labels:
    clusterctl.cluster.x-k8s.io/move-hierarchy: "true"
  name: trial-credentials
spec:
  allowedNamespaces: {}
  clientID: 096cc0f9-fecb-4109-b5ee-faeb38610624
  clientSecret:
    name: cluster-identity-secret # kubectl create secret generic "${AZURE_CLUSTER_IDENTITY_SECRET_NAME}" --from-literal=clientSecret="${AZURE_CLIENT_SECRET}"
    namespace: default
  tenantID: 699c5ef4-217b-449a-a06a-1b8002557aea
  type: ServicePrincipal
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: trial-cluster
  namespace: default
spec:
  clusterNetwork:
    services:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedControlPlane
    name: trial-cluster-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureManagedCluster
    name: trial-cluster
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedControlPlane
metadata:
  name: trial-cluster-control-plane
  namespace: default
spec:
  identityRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: AzureClusterIdentity
    name: trial-credentials
    namespace: default
  location: westeurope
  resourceGroupName: trial-cluster
  nodeResourceGroupName: trial-cluster-agentpools
  subscriptionID: e054c9f5-d781-4a83-a835-2296004b9fe6
  version: v1.24.3
  networkPolicy: calico 
  networkPlugin: azure
  sku:
    tier: Free
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedCluster
metadata:
  name: trial-cluster
  namespace: default
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: syspool
  namespace: default
spec:
  clusterName: trial-cluster
  replicas: 1
  template:
    spec:
      bootstrap:
          dataSecretName: ""
      clusterName: trial-cluster
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: syspool
        namespace: default
      version: v1.24.3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: syspool
  namespace: default
spec:
  mode: System
  osDiskSizeGB: 30
  sku: Standard_D2s_v3
  scaling:
    minSize: 1
    maxSize: 10
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: usrpool
  namespace: default
spec:
  clusterName: trial-cluster
  replicas: 1
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: trial-cluster
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: AzureManagedMachinePool
        name: usrpool
        namespace: default
      version: v1.24.3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureManagedMachinePool
metadata:
  name: usrpool
  namespace: default
spec:
  mode: User
  osDiskSizeGB: 40
  sku: Standard_D2s_v4
  scaling:
    minSize: 1
    maxSize: 10
  nodeLabels:
    app.farfetch.ftech/node-role: "user"
    app.farfetch.ftech/node-pool-priority: "standard"